before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/datadog-backup/main.go
    binary: datadog-backup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
dockers:
  - image_templates:
      - matlockx/datadog-backup
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^images'